# Generated by Django 5.2 on 2025-05-09 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="prompt_type",
            field=models.CharField(default="prompt_1", max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
